//LISTA POKEMONS
export const READ_POKEMONS = "READ_POKEMONS"
export const NEXT_URL = "NEXT_URL";
export const PREV_URL = "PREV_URL";

//AGREGAR O ELIMINAR POKEMON DE LA LISTA
export const ADD_POKEMON = "ADD_POKEMON"
export const REMOVE_POKEMON = "REMOVE_POKEMON"

//AGREGA O ELIMINA FAVORITO
export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";